name: aprendize
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.40.0
  image_picker: ^0.8.7+3 # Check for the latest version on pub.dev

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/

